version: '3'

services:
  nginx:
    container_name: lemp_nginx2
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html

      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    ports:
      - "82:80"
    
    # network fron and back
    networks:
      - front-tier
      - back-tier

  php:
    container_name: lemp_php2
    build: php/
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
    # set network back-tier
    networks:
      - back-tier

  
  
  phpmyadmin:
      image: 'phpmyadmin/phpmyadmin:latest'
      container_name: phpmyadmin2
      restart: always
      ports:
        - 8080:80
      # set network back-tier
      networks:
        - back-tier
      #link:
        #- mysql:mysql
      environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - PMA_HOST = db
      
  db:
    container_name: lemp_mariadb2
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # set network back-tier
    networks:
      - back-tier

#networks:
#  default:
#    name: web_network
#    external: true

networks:
  front-tier: {}
  back-tier: {}       